### ISSUE TITLE
Google Sign-In Shouldn't Happen on Start-up

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/weasis-chcapi-extension#1]
Right now Google sign-in happens when the plugin get's loaded. There should be a dedicated "Sign-in" button instead.

**Comment by dzelemba** [comment]
Update: there is a dedicated sign-in button, but on Linux sign in happens automatically when the plugin get's loaded. On MacOS no sign-in happens until the "Google sign-in" button is clicked, which is the desired behavior.

**Comment by red1408** [comment]
From my testing automatic sign-in happens only if I have interrupted sign-in process and force-closed Weasis before that.
Which is still a bug of course, I'm just checking whether there are other ways to run into this situation.
