### ISSUE TITLE
Linux: Google sign-in requires clicking link in terminal output

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/weasis-chcapi-extension#2]
The application should open the browser window for you instead of you having to look through the terminal output. This only happens on Linux, not Mac.

**Comment by pavertomato** [comment]
seems like this is reproducible only if system won't able to open default browser, which seems like valid behavior

**Comment by dzelemba** [comment]
Hmm can it create a popup that asks the user to naviagte to a given URL instead of printing to stdout in this case?

**Comment by pavertomato** [comment]
yeah, seems it could be done by adding some code to default implementation of browser runner

**Comment by mukhlin** [comment]
The authorization URL is long enough and popup dialog will be too wide. I implemented it as follows:
![popup](https://user-images.githubusercontent.com/50941274/58449923-dd264280-8136-11e9-8caa-adfe80946532.png)
