### ISSUE TITLE
Automate Release

### ISSUE THREAD

**Issue by poojavenkatram** [GoogleCloudPlatform/weasis-chcapi-extension#24]

**Comment by poojavenkatram** [comment]
I have opened the Wiki here as well - can we please add the steps. I will follow those to release a new release and close this issue :)

**Comment by poojavenkatram** [comment]
Released a new version following the Wiki and it works great - thanks for writing it up.

**Comment by pavertomato** [comment]
> Released a new version following the Wiki and it works great - thanks for writing it up.

seems like trigger wasn't created and artifact wasn't published to release page, but seems like now we able to create triggers for gcp-healthcare-oss-test, so i've created trigger for weasis and for qupath:

https://console.cloud.google.com/cloud-build/triggers/8bdb9564-f610-47a4-bba6-cc6086bd5a09?project=gcp-healthcare-oss-test

https://console.cloud.google.com/cloud-build/triggers/c2087edc-fa25-4eac-ac71-5c3420f6843f?project=gcp-healthcare-oss-test

you'll need to delete existing tag(or iterate version once more)
https://stackoverflow.com/questions/5480258/how-to-delete-a-remote-tag
and do release process  again unfortunately  
example of successful trigger https://console.cloud.google.com/cloud-build/builds/8f8e1b18-b8e6-4f95-adee-c2403c0b6675?project=healthcare-api-215503&organizationId=345190292651
example of successful release https://github.com/pavertomato/weasis-chcapi-extension/releases/tag/v5

**Comment by poojavenkatram** [comment]
I do see the release here though: https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/releases

**Comment by poojavenkatram** [comment]
Oh but the jar wasn't created ok makes sense

**Comment by poojavenkatram** [comment]
When I try to push the JAR three builds were started and atleast one (if not more) failed - can you please take a look?

**Comment by pavertomato** [comment]
https://github.com/GoogleCloudPlatform/qupath-chcapi-extension/issues/12


for weasis - versions of dependency and application was glued together
PR to fix this GoogleCloudPlatform/weasis-chcapi-extension#31

**Comment by poojavenkatram** [comment]
Thanks - I have added a new release and confirmed that the JAR is present.
