### ISSUE TITLE
incorrect display of multiseries studies

### ISSUE THREAD

**Issue by pavertomato** [GoogleCloudPlatform/weasis-chcapi-extension#7]
if study is multiseries, frames from all series will be displayed as one series.

if these series multiframe, then frames will be displayed with strange sequence - sorted by frame first

> series0frame0-series1frame0-series2frame0-series0frame1...

also if sum of all series is more than some limit, extension will fail to display frames as described #6

**Comment by pavertomato** [comment]
seems like it made in purpose, extension downloads all series, sort frames and after what displays all of them as one instance, shall we keep this logic, or change it to open all instances of study in separate tabs?

**Comment by poojavenkatram** [comment]
We should have the behavior consistent with the rest of Weasis - so whatever is the behavior for this usecase in other flows like reading a study from local disk in Weasis we should do the same here.

**Comment by nroduit** [comment]
From the version [3.5.4,](https://github.com/nroduit/Weasis/releases/edit/3.5.4-rc) a solution to manage downloads would be to use the new dicom:rs command:

Add new command dicom:rs:
```Load DICOM files from DICOMWeb API (QIDO/WADO-RS)
Usage: dicom:rs -u URL -r QUERYPARAMS... [-H HEADER]... [--query-header HEADER]... [--retrieve-header HEADER]... [--query-ext EXT] [--retrieve-ext EXT] [--accept-ext EXT]
  -u --url=URL               URL of the DICOMWeb service
  -r --request=QUERYPARAMS   Query params of the URL, see weasis-pacs-connector
  -H --header=HEADER         Pass custom header(s) to all the requests
  --query-header=HEADER      Pass custom header(s) to the query requests (QIDO)
  --retrieve-header=HEADER   Pass custom header(s) to the retrieve requests (WADO)
  --query-ext=EXT            Additionnal parameters for Query URL (QIDO)
  --retrieve-ext=EXT         Additionnal parameters for Retrieve URL (WADO)
  --accept-ext=EXT           Additionnal parameters for DICOM multipart/related Accept header of the retrieve URL (WADO). Default value is: transfer-syntax=*
  -? --help                  show help
```
This will allow to better managing the download process (preference of concurrent downloads, pause/resume at series level or globally, change dynamically the priority of series to download).

**Comment by poojavenkatram** [comment]
Because every series is displayed in it's own tab for now - we can keep it this way and change it if someone makes a request.
